### ISSUE TITLE
Improve filelist appearance

### ISSUE THREAD

**Issue by dimonomid** [vifm/vifm#289]
Hi,

One of the things I desperately miss in vifm is a customizability of how to display files depending on their type, modification date, etc.

The most obvious thing which I'd like to be able to customize is the color. I see that the current implementation of color scheme is rather limited: there is a hardcoded number of things which could be highlighted differently ( https://github.com/vifm/vifm/blob/master/src/ui/colors.h#L34 ), and that's it: no way to highlight depending on the filetype or modification time. So I acknowledge that this is a non-trivial piece of work. Still, just want to start a discussion, and maybe one day, who knows, it might be implemented :)

Personally, I find highlighting based on the modification time to be extremely useful: say, in another file manager, I have a dedicated color for the files modified within the last minute, and another color for those modified within the last hour. It comes in extremely handy in my daily life.

Highlighting based on file extension is also useful, of course. I don't have a separate color for tons of file types I work with, but a handful of most-frequently used is still useful.

However, other than colors, I'm wondering about another way to distinguish files based on their types: icons. Of course we can't use graphics because it's just a terminal (and that's great), but we can use utf-8 characters, and there is a lot of them. Combined with the fact that the icon might have a color which is different from the filename's color, it has a very good potential on providing a rich UI, in my opinion. Someone might dislike this kind of "rainbow", but I would love it.

One obvious application of it is to use a "folder" icon for directories: 📁.

```
📁 dir1
📁 dir2
  regular_file
```

If I were implementing it, I'd probably provide a way for the user to just specify arbitrary prefix based on the file type, etc. So, in (yaml-ish) pseudocode, settings might look like:

```yaml
dirs:
  prefix: "📁 "
  prefix_color: "yellow" # of course the exact color should be specified in the color scheme, so
                         # we need a bit of indirection here;
                         # just didn't bother to be a purist in that example
default:
  prefix: "  "
```
If a user prefers all files to be indented by the same number of chars, they would have a default prefix `  ` as in the example above; otherwise an empty prefix would make files non-indented, thus saving some space.

Anyway, there were my broad ideas on how I would improve vifm appearance if I had enough time, so just decided to share that and I'd love to know what do you think about it :)
