### ISSUE TITLE
Missing autoload scripts in vim's addon directory when installing via apt

### ISSUE THREAD

**Issue by benelan** [vifm/vifm#989]
Hi! When installing via apt, vifm's vim plugin gets added to vim's addons. However, the autoload scripts are missing, which causes startup errors when adding `/usr/share/vim/addons` to the runtime path:

```vim
if isdirectory("/usr/share/vim/addons")
    set runtimepath+=/usr/share/vim/addons
endif
```

Here is the error:

```
Error detected while processing /usr/share/vim/addons/plugin/vifm.vim:
line   60:
E117: Unknown function: vifm#globals#Init
Press ENTER or type command to continue
```

Here is the registry file showing that the autoload scripts are missing:

```yaml
# /usr/share/vim/registry/vim-vifm.yaml
addon: vifm
description: interface to the vifm file manager
files:
  - ftdetect/vifm-rename.vim
  - ftdetect/vifm.vim
  - ftplugin/mail_vifm.vim
  - ftplugin/vifm-edit.vim
  - ftplugin/vifm.vim
  - ftplugin/vifm-cmdedit.vim
  - ftplugin/vifm-rename.vim
  - plugin/vifm.vim
  - doc/vifm-app.txt
  - doc/vifm-plugin.txt
  - syntax/vifm.vim
```

Note this may be fixed already, but it's an apt-specific issue, and apt is still on vifm `v0.12-1`.
